version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - prod-network
    restart: unless-stopped
    volumes:
      - nginx_data:/usr/share/nginx/html

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - prod-network
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    networks:
      - prod-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nosql_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    networks:
      - prod-network
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  message_broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management interface port
    networks:
      - prod-network
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  nginx_data:
  redis_data:
  postgres_data:
  mongo_data:
  rabbitmq_data:


networks:
  prod-network:
    external: true